default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: apollo_demo


development:
  <<: *default
  database: apollo_demo_dev

test: &test
  <<: *default
  database: apollo_demo_test

production:
  <<: *default
  database: apollo_demo_prod
